---
development:
  cloud_name: cloudinary-oncase
  api_key: '922961327364282'
  api_secret: 4rPUnQu4q1wU73KHih5MFBo7awE
  enhance_image_tag: true
  static_image_support: false
docker:
  cloud_name: cloudinary-oncase
  api_key: '922961327364282'
  api_secret: 4rPUnQu4q1wU73KHih5MFBo7awE
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: cloudinary-oncase
  api_key: '922961327364282'
  api_secret: 4rPUnQu4q1wU73KHih5MFBo7awE
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: cloudinary-oncase
  api_key: '922961327364282'
  api_secret: 4rPUnQu4q1wU73KHih5MFBo7awE
  enhance_image_tag: true
  static_image_support: false
