default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: site-oncase_development

test:
  <<: *default
  database: site-oncase_test

docker:
  <<: *default
  database: site-oncase_docker
  host: db
  username: postgres

production:
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("DB_NAME") { 5 } %>
  username: <%= ENV.fetch("DB_USER") { 5 } %>
  password: <%= ENV.fetch("DB_PASS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { 5 } %>
  reconnect: true